[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
version_files = [
    "VERSION",
    "ui/package.json:version",
    "server/pyproject.toml:version",
    "ml-server/pyproject.toml:version"
]
tag_format = "v$version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
