# Dev
services:
    traefik:
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--api.insecure=true"
        ports:
            - 8080:8080
    ui:
        build:
            context: ./ui
            target: dev
        volumes:
            - ./ui/src:/app/src
            - ./ui/public:/app/public
            - ./ui/package.json:/app/package.json
            - ./ui/package-lock.json:/app/package-lock.json
    postgres:
        ports:
            - 5432:5432

    server:
        build:
            context: ./server
            target: dev
        volumes:
            - ./server/src:/app/src
            - ./server/.env:/app/.env
            - ./server/migrations:/app/migrations
        env_file:
            - "./server/.env"
        ports:
            - 8000:8000

    ml-server:
        build:
            context: ./ml-server
            target: dev
        volumes:
            - ./ml-server/src:/app/src
            - ./ml-server/.env:/app/.env
        env_file:
            - "./ml-server/.env"
        ports:
            - 5000:5000
