{
 "title": "Invoice Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Higher request time (ms) - P95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_request_duration_highr_seconds_bucket[10m])) by (le)\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Higher request time (ms) - P99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(http_request_duration_highr_seconds_bucket[10m])) by (le)\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_requests_total{handler!~\"/|/metrics|/openapi.json|none|/docs\"}[5m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "2xx Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{handler!~\"/docs|/openapi.json|none|/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (\r\n  http_requests_total{\r\n    handler!~\"/metrics|none|^/$\",  # Exclude metrics, undefined handlers, and root\r\n    method!=\"OPTIONS\"              # Exclude OPTIONS requests\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by(handler) (rate(http_request_duration_seconds_sum{handler!~\"/docs|/openapi.json|/metrics|none|/\"}[5m])) * 1000\r\n) \r\n/ \r\n(\r\n  sum by(handler) (rate(http_request_duration_seconds_count{handler!~\"/docs|/openapi.json|/metrics|none|/\"}[5m])) > 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}