apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-ui
  namespace: invoice
  labels:
    app: invoice-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-ui
  template:
    metadata:
      labels:
        app: invoice-ui
    spec:
      containers:
      - name: invoice-ui
        image: ghcr.io/jeremyarancio/invoice-ui:latest
        # image: invoice-ui
        # imagePullPolicy: Never # Force Kube to pull image locally
        ports:
        - containerPort: 5173
        env:
          - name: VITE_SERVER_API_URL
            valueFrom:
              configMapKeyRef:
                name: invoice-configmap
                key: VITE_SERVER_API_URL

---

apiVersion: v1
kind: Service
metadata:
  name: invoice-ui-service
  namespace: invoice
spec:
  selector:
    app: invoice-ui
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
