apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: invoice
  name: invoice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 