blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/your-username/invoice-reader-app/discussions
    about: For questions or general discussions, please use GitHub Discussions
