name: Feature Request
description: Suggest a new feature or enhancement for the invoice reader app
title: "[Feature]: "
labels: ["UX", "UI", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Please describe your feature request.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true
