{
 "title": "Invoice Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Higher request time (ms) - P95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_request_duration_highr_seconds_bucket[5m])) by (le)\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Higher request time (ms) - P99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(http_request_duration_highr_seconds_bucket[5m])) by (le)\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler!~\"/|/metrics|/openapi.json|none|/docs\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "2xx Status",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total[5m])) by (status)\r\n  /\r\n  sum(rate(http_requests_total[5m]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{handler!~\"/docs|/metrics|/openapi.json|none\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(handler) (rate(http_request_duration_seconds_sum{handler!~\"/docs|/openapi.json|/metrics|none\"}[5m])) / sum by(handler) (rate(http_request_duration_seconds_count[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}