"""Initial migration

Revision ID: 08b0ecda8805
Revises: 
Create Date: 2025-01-17 11:33:10.541170

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '08b0ecda8805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
