"""Initial migration

Revision ID: 373d96d7f878
Revises:
Create Date: 2025-01-17 12:36:13.598533

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "373d96d7f878"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice",
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "invoice",
        sa.Column("is_paid", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice", "is_paid")
    op.drop_column("invoice", "currency")
    # ### end Alembic commands ###
