global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
          - server
        type: A
        port: 8000
