"""Add currencies

Revision ID: 52a7478747a7
Revises: 9ef3fa9f1cc8
Create Date: 2025-03-13 15:57:45.285540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52a7478747a7'
down_revision: Union[str, None] = '9ef3fa9f1cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoice', sa.Column('currency_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'invoice', 'currency', ['currency_id'], ['id'])
    op.drop_column('invoice', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'currency_id')
    op.drop_table('currency')
    # ### end Alembic commands ###
