"""Update invoice

Revision ID: a2b3013b84b4
Revises: 52a7478747a7
Create Date: 2025-06-18 07:33:56.713455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2b3013b84b4"
down_revision: Union[str, None] = "52a7478747a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("paid_date", sa.Date(), nullable=True))
    op.alter_column("invoice", "currency_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("invoice", "is_paid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice",
        sa.Column("is_paid", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column("invoice", "currency_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("invoice", "paid_date")
    # ### end Alembic commands ###
